project_identifier: 'safeway-api'
api_key: '428e5ad6d2bf853dab15babbd0e7942d' #can be found in your project settings page
base_path: './'
preserve_hierarchy: true

files:
  - source: '/docs/*.md'
    translation: '/website/translated_docs/%locale%/%original_file_name%'
    languages_mapping: &anchor
      locale:
        'pt-BR': 'pt-BR'
  - source: '/website/i18n/en.json'
    translation: '/website/i18n/%locale%.json'
    languages_mapping: *anchor
